### ISSUE TITLE
Training on variable input size

### ISSUE THREAD

**Issue by dokutagero** [wkentaro/fcn#101]
First of all thanks for the code, I´m new to Chainer and I find the code very clean.

I´m going to try to use FCN for a segmentation problem but I have one doubt from the code. In the FCN32 model, after the Deconvolution2D there is a hardcoded crop.

```
h = self.upscore(score_fr)
h = h[:, :, 19:19 + x.data.shape[2], 19:19 + x.data.shape[3]]
```

This crop is due to a particular size for the training set, right?

**Comment by wkentaro** [comment]
I answered the question at https://github.com/wkentaro/pytorch-fcn/issues/51#issuecomment-324423289.

**Comment by dokutagero** [comment]
Awesome! Thank you very much for your prompt reply :)

**Comment by wkentaro** [comment]
Your welcome:)
