### ISSUE TITLE
Learnable Deconvolution weights question

### ISSUE THREAD

**Issue by dokutagero** [wkentaro/fcn#104]
Hello wkentaro,

One more time, thank you for your awesome contribution. I have a question regarding the upsampling in your implementation. Even though the Deconvolution2D links are initialized with weights, all of them are learnable and don't have the weights fixed, right?

**Comment by wkentaro** [comment]
The weight is fixed and is not updated during training, as do so in the original work.
https://github.com/wkentaro/fcn/blob/master/examples/voc/train_fcn32s.py#L71

**Comment by dokutagero** [comment]
Thanks for the reply. I was asking because I was not sure if I couldn't find explicitly if the layer was frozen so it was not used in backprop to update the weights. Does it get frozen explicitly or just by initializing the weights they ddon't get updated?

**Comment by wkentaro** [comment]
What is the difference b/w "get frozen explicitly" and "just by initializing the weights they ddon't get updated"?

**Comment by dokutagero** [comment]
I thought the weight initialization would be related only to the values when starting to train (instead of random initialization) but they would get updated if the weight update is not disabled explicitly when creating the layer.

**Comment by wkentaro** [comment]
Ok.
So, I mean the weight is fixed after initialization explicitly and is not updated during training.

**Comment by dokutagero** [comment]
Thank you for your reply. Just to understand it, where is it specified not to update the parameters of the deconvolution2d layers? My doubt is because I don't see any difference in the way of instantiating a deconvolution2d layer and a convolution2d, only that the weights for the deconvolution are initialized as bilinear interpolation. I don't know if I'm making myself clear, but I don't see exactly how a convolution2d is learning the weights and a deconvolution2d is fixed.

**Comment by dokutagero** [comment]
Oh ok, I'm sorry, I didn't see this line of code: ```model.upscore.disable_update()```

**Comment by dokutagero** [comment]
I was looking at the ```disable_update()``` in the model but it's in the main training script. Thank you very much!

**Comment by wkentaro** [comment]
:+1:
