### ISSUE TITLE
could not train VOC2012 datasets by using fcn_train.py

### ISSUE THREAD

**Issue by jinhang** [wkentaro/fcn#44]
hi, i installed the VOC2012 datasets in "fcn/data/pascal/VOC2012", and put the "vgg16.chainermodel" on "fcn/data", all i want to do is train the VOC2012 datasets, but it failed, what's the problem?
![fcn-error](https://cloud.githubusercontent.com/assets/4497831/16979364/3685efd0-4e93-11e6-827f-168004602c32.png)

**Comment by wkentaro** [comment]
Thank you for the report. 
@jinhang #45 will fix it.

**Comment by jinhang** [comment]
i have read the closed problem [#20](https://github.com/wkentaro/fcn/pull/20), you succeed in training datasets.  where is the difference, environment or code, thank you!

**Comment by wkentaro** [comment]
I merged #45 right now. Please try the training script again.

**Comment by jinhang** [comment]
i will try, thank you!

**Comment by jinhang** [comment]
it works, thank you!
