### ISSUE TITLE
How to train our own datasets

### ISSUE THREAD

**Issue by jinhang** [wkentaro/fcn#47]
hi, sorry to interrupt you again.
I want to train my own datasets(just 2 classes),  i think i have changed all the code that needs to be changed, but there are still some problems, can you give an instruction on how to train my own datasets? Thanks
![train_error](https://cloud.githubusercontent.com/assets/4497831/17010214/7a5cf8ba-4f34-11e6-9907-28b35723bb49.png)

**Comment by wkentaro** [comment]
It seems that you need to use larger GPU memory.

**Comment by jinhang** [comment]
My GPU is Titan x (12GB)
For demo, i just used 240 pictures, i think there's a problem with the code, any suggestion?

**Comment by wkentaro** [comment]
Maybe you are using too large image for the input to the network.

**Comment by jinhang** [comment]
all pictures occupy 149Mb,is it large?

**Comment by wkentaro** [comment]
I mean the size of input array.
I use around 500 x 500 x 3 array with batch size 1. 
so the size is 750000.

**Comment by jinhang** [comment]
in your code,your image size is <= 500*500?

**Comment by wkentaro** [comment]
Yeah. like: https://github.com/wkentaro/fcn/blob/master/examples/apc2016/apc2016.py#L144
