### ISSUE TITLE
Binary Training

### ISSUE THREAD

**Issue by luiscarm9** [wkentaro/fcn#56]
I'm trying to change your code for a binary problem.
After I train and use the new model get the following result in one of the test images
![image-179](https://cloud.githubusercontent.com/assets/11293873/18857781/590e8f48-842c-11e6-9bee-811f3842cee2.jpg)
Do you have any clue why the predicted image have that resolution issue in the labels box.
And why i get that red noise when i look in the prediction i don't get any positive so there is no reason for that points.

**Comment by wkentaro** [comment]
What do you mean with resolution issue?

**Comment by luiscarm9** [comment]
Was an issue with training image size from training dataset. 
Solved
