### ISSUE TITLE
Training from scratch

### ISSUE THREAD

**Issue by aleksandrmelnyk** [wkentaro/fcn#58]
Sorry, am  kinda new to FCN. 
Why we are using pretrained model, can we train from scratch on cusrom dataset in scripts/fcn_train.py?

thanks,

Alex.

**Comment by wkentaro** [comment]
> Why we are using pretrained model

To train the network with less time.

> can we train from scratch on cusrom dataset in scripts/fcn_train.py?

You can disable the copy of weight of pretrained model.

**Comment by aleksandrmelnyk** [comment]
Thanks much Kentaro,
I'll try that.
