### ISSUE TITLE
how to get feature map ?

### ISSUE THREAD

**Issue by dxiaosa** [wkentaro/fcn#67]
I want to get intermediate layers, like conv_1, conv_2, feature map for visualization. So what should I do?

**Comment by wkentaro** [comment]
You can set `self.h_conv1_1 = h` here: https://github.com/wkentaro/fcn/blob/master/fcn/models/fcn8s.py#L54
and access the attribute with `model.h_conv1_1` here: https://github.com/wkentaro/fcn/blob/master/examples/pascal/infer.py#L45

**Comment by dxiaosa** [comment]
thx, I will have a try. And can I train fcn_8s?

**Comment by wkentaro** [comment]
I haven't try it, but I think you can as I did for fcn32s: https://github.com/wkentaro/fcn/blob/master/examples/pascal/train_fcn32s.py
Maybe you should copy the pretrained weight of fcn32s and fcn16s before training fcn8s.

**Comment by dxiaosa** [comment]
Sorry, I can't understand you.  because i don't find like "pretraind weight" parameter in fcn16s.py or train_fcn32.py. So, can you have a detailed illustration?

**Comment by dxiaosa** [comment]
set ‘self.h_conv1_1 = h ’  is useful. thanks!

**Comment by wkentaro** [comment]
> Sorry, I can't understand you. because i don't find like "pretraind weight" parameter in fcn16s.py or train_fcn32.py. So, can you have a detailed illustration?

On training FCN32s, we copy the pretrained weights from VGG16 to FCN32s: https://github.com/wkentaro/fcn/blob/master/fcn/trainers/fcn32s.py#L56
And I think it is necessary that you copy the pretrained weights from FCN32s to FCN16s after training the FCN32s, and you do the same for FCN8s.

**Comment by dxiaosa** [comment]
@wkentaro  OK, I will try again, and tell you what's going on!

**Comment by dxiaosa** [comment]
@wkentaro 

I established a new script most content copying from FCN32s and modified some lines:

  # 2. model
    n_class = len(dataset_train.label_names)

    pretrain32_path = './fcn/model/FCN32s_trainer_iter_40.h5'
    pretrain32 = fcn.models.FCN32s(n_class=n_class)
    chainer.serializers.load_hdf5(pretrain32_path, pretrain32)

    model = fcn.models.FCN16s(n_class=n_class)
    model.train = True
    fcn.util.copy_chainermodel(pretrain32, model)


However, error occurred:


  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py/_objects.c:2582)

  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py/_objects.c:2541)

  File "h5py/h5g.pyx", line 151, in h5py.h5g.create (-------src-dir-------/h5py/h5g.c:2676)

ValueError: Unable to create group (No write intent on file).


So, what should I do?

**Comment by wkentaro** [comment]
> ./fcn/model/FCN32s_trainer_iter_40.h5

This is wrong.

It should be FCN32s_model_iter_XXX.h5

**Comment by dxiaosa** [comment]
@wkentaro  I have seen that:

    def __call__(self, x, t=None):
        self.x = x
        self.t = t

        # conv1
        h = F.relu(self.conv1_1(x))
        conv1_1 = h

I added the following line as you said above:
        self.h_conv1_1 = h
so, what is the different parameter 'conv1_1' and 'self.h_conv1_1'?  I can understant that h is the feature map. and I try access conv1_1.W.data, it is likely the weights matirx of conv1_1 layer.

**Comment by wkentaro** [comment]
self.conv1_1 is convolutional layer, h_conv1_1 is hidden layer.

**Comment by dxiaosa** [comment]
However, when I  imshow the h_conv1_1, it is the feature map!

**Comment by wkentaro** [comment]
I mean the feature map with hidden layer.

**Comment by wkentaro** [comment]
h_conv1_1 is hidden unit, self.conv1_1.param is the weight and bias.

**Comment by wkentaro** [comment]
@dxiaosa So your problem is fixed? Or still you have some problems to get the feature map?

**Comment by dxiaosa** [comment]
ok. it is solved! thx!!  And, I have another question, when I train fcn16s or fcn8s, why the file /fcn/examples/pascal/logs/latest/log.json have no report about any accuracy? I just change the pre-trained FCN32s_model_iter_XXX.h5 for fcn16s used, and others keep the same.

**Comment by wkentaro** [comment]
You need to do like this: https://github.com/wkentaro/fcn/blob/master/fcn/models/fcn32s.py#L131

**Comment by dxiaosa** [comment]
@wkentaro  it works! thank you!
