### ISSUE TITLE
Can't run pascal example

### ISSUE THREAD

**Issue by rcalland** [wkentaro/fcn#68]
when trying to run `fcn/examples/pascal/train_fcn32s.py`, the program fails at the `download_vgg16_chainermodel()` function, probably because the program `gdown` is not found. I cannot find any information about gdown, how can I get it? Thanks!

**Comment by wkentaro** [comment]
`gdown` is defined in `requirements.txt`.

**Comment by rcalland** [comment]
Ah ofcourse.... got it, thanks!
