### ISSUE TITLE
GPU use check in Inferencer seems incorrect

### ISSUE THREAD

**Issue by mizti** [wkentaro/fcn#82]
Hi, thanks for sharing fcn with chainer code!

I found a possible bug, in Inference.infer_image_file,
in this method gpu availability is check with:

    if self.gpu >= -1:

, but I wonder this should be:

    if self.gpu > -1:

If self.gpu is checked with self.gpu >= -1, input data is translated into cuda
even with cpu mode params like

    fcn_infer.py --img-files sample.jpg --gpu -1  # cpu mode

If this is not a bug, but a intentional code, sorry and just ignore this issue.

**Comment by wkentaro** [comment]
Thank you. That seems a bug.
