### ISSUE TITLE
How to get training feature maps?

### ISSUE THREAD

**Issue by dxiaosa** [wkentaro/fcn#91]
Last time, we resolved the problem of fetching the feature maps off line, ie. in testing program. So, if I want to get the feature maps when training, how can I do? Thx.

**Comment by wkentaro** [comment]
Do you mean the feature maps are the outputs of each hidden layer?
If so, you can get them by setting `self.conv1_1 = h` here: https://github.com/wkentaro/fcn/blob/master/fcn/models/fcn32s.py#L54
and `self.model.conv1_1` in the test program.
