### ISSUE TITLE
how to implement fcn with chainer

### ISSUE THREAD

**Issue by zhangfanqie** [wkentaro/fcn#94]
Hi, me again! I'm new to image segmentation.I want to try chainer this time.
But I don't know the relationship between this fcn folder and chainer.
Do I need to install chainer first?
Should this fcn be put into chainer foler or somewhere?
And how to set the PYTHONPATH?

Thanks a lot!!!

**Comment by wkentaro** [comment]
fcn depends on chainer so it is automatically installed via `pip install fcn`
see https://github.com/wkentaro/fcn#installation for detail.
