### ISSUE TITLE
what can I do if I don't use pre-trained model (VGG16) to start training?

### ISSUE THREAD

**Issue by dxiaosa** [wkentaro/fcn#96]
what can I do if I don't use pre-trained model (VGG16) to start training? Annother condition is that if I modify the layer structure in script fcn32s.py that mismatches the structure of pre-trained model(VGG16), such as deleting convolution layer 5, and processes will break down?

**Comment by wkentaro** [comment]
FCN requires pre-trained model trained in ImageNet, though it is reasonable if you train it by other dataset.
I think it is possible for you to delete some layer to create smaller network.

**Comment by dxiaosa** [comment]
However,  when I commnent this line in FCN32s.py:

 fcn.util.copy_chainermodel(vgg, model)

that means pre-trained model unused in process of training. It also works.

**Comment by dxiaosa** [comment]
And, when I delete the convolution layer conv_2 in traing process with pre-trained model like this:

    def __init__(self, n_class=21):
        self.n_class = n_class
        super(self.__class__, self).__init__(
            conv1_1=L.Convolution2D(3, 64, 3, stride=1, pad=100),
            conv1_2=L.Convolution2D(64, 64, 3, stride=1, pad=1),

            conv2_1=L.Convolution2D(64, 128, 3, stride=1, pad=1),
            #conv2_2=L.Convolution2D(128, 128, 3, stride=1, pad=1),

it broke down!  So I wonder how  weights are copied from pre-trained model to our defined model?

**Comment by wkentaro** [comment]
`fcn.util.copy_chainermodel` copies if link name and its weight shape is the same.
I have used at past, but recently I manually copies weight: https://github.com/wkentaro/fcn/blob/master/examples/voc/train_fcn32s.py#L52

**Comment by dxiaosa** [comment]
Dose It mean that each layer from pre-trained weights can be dicided whether it will be imported?  So, for example, I can import conv_1 but not import conv_2 like tensorflow?

**Comment by wkentaro** [comment]
Yeah, I think you can do it.

**Comment by dxiaosa** [comment]
OK, thanks.  I will try it.
