### ISSUE TITLE
Issue with inferencing using fcn_infer.py

### ISSUE THREAD

**Issue by karttikeya** [wkentaro/fcn#97]
I have no idea if how to correct this without changing the internal code:

![image](https://user-images.githubusercontent.com/10197226/28265687-f9d0e94e-6b2b-11e7-83d9-c3709024c7cf.png)

**Comment by wkentaro** [comment]
Thanks! I fixed it.

**Comment by wkentaro** [comment]
I released 6.0.4, so please run `pip install -U fcn` to fix this issue on your environment.

**Comment by karttikeya** [comment]
Sure. Thanks for the quick response.
