### ISSUE TITLE
Can't do training!

### ISSUE THREAD

**Issue by najaxel** [wkentaro/fcn#98]
Hi Kentaro,

Training is not working for me. Whenever I run **./examples/voc/train_fcn*s.py --gpu 0**, I get the following error message:

**IOError: [Errno 2] No such file or directory: '~data/models/chainer/fcn16s_from_caffe.npz'**

Why does it assume that data and models exists on this path **'~data/models/chainer/** ?

I desperately created this folder and put .npz file there but still it didn't work.

Any help is appreciated!

Thanks!

**Comment by knorth55** [comment]
did you read readme?
have you done `./download_dataset.py`?

https://github.com/wkentaro/fcn/blob/6a32e13d00f3cedfdcc00ee170784867639b17df/examples/voc/README.md
