### ISSUE TITLE
Download script for datasets fail to cover all datasets used in voc example

### ISSUE THREAD

**Issue by najaxel** [wkentaro/fcn#99]
Hi,

I'm re-posting here Issue #98 which is still unsolved:

Here is a summary of what I'm facing:

1) I have read the readme already.
2) I downloaded FCN as mentioned: **pip install fcn** and it worked well.
3) Inference worked perfectly.
4) However, training is not working for me. Here is what I did:
    (a) Downloaded dataset using: **./download_dataset.py**
    (b) Downloaded models using: **./download_models.py**
    (c) Attempted training using: **./train_fcn*s.py --gpu -0** however it failed! Here is the error message: 

    *IOError: [Errno 2] No such file or directory: '~/data/datasets/VOC/benchmark_RELEASE/dataset/train.txt'*

5) Also evaluation didn't work! I did it as described in the readme: 
**./evaluate.py ~data/models/chainer/fcn8s_from_caffe.npz**
Here is the error message:
*IOError: [Errno 2] No such file or directory: '~data/datasets/VOC/VOCdevkit/VOC2011/ImageSets/Segmentation/train.txt'*

What's going on? I appreciate your help.

And please don't close this issue too soon this time!

Thanks!

**Comment by wkentaro** [comment]
Please download datasets from below links:
- https://github.com/wkentaro/fcn/blob/master/fcn/datasets/voc.py#L95
- https://github.com/wkentaro/fcn/blob/master/fcn/datasets/voc.py#L124

**Comment by wkentaro** [comment]
@najaxel I think your problem is fixed in current master branch. Please try below:

```
./download_datasets.py
./download_models.py
./train_fcn*s.py --gpu=0
```

**Comment by najaxel** [comment]
@wkentaro thanks a lot for the fix! it works now.
